# Generated by Django 3.0.8 on 2020-08-07 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200807_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 8, 24, 53, 969377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=models.TextField(max_length=200),
        ),
    ]
